export const filterDebuts = {
  title: `Debuts`,
  fields: [
    { label: `Manga`, value: `manga` },
    { label: `Anime`, value: `anime` },
    { label: `Novel`, value: `novel` },
    { label: `Movie`, value: `movie` },
    { label: `Game`, value: `game` },
    { label: `Ova`, value: `ova` },
  ],
};

export const filterClassifications = {
  title: `Classifications`,
  fields: [
    { label: `Senjutsu`, value: `Senjutsu` },
    { label: `General skill`, value: `General skill` },
    { label: `Space-Time Ninjutsu`, value: `Space-Time Ninjutsu` },
    { label: `Regeneration Techniques`, value: `Regeneration Techniques` },
    { label: `Hiden`, value: `Hiden` },
    {
      label: `Chakra Absorption Techniques`,
      value: `Chakra Absorption Techniques`,
    },
    { label: `Chakra Flow`, value: `Chakra Flow` },
    { label: `Shurikenjutsu`, value: `Shurikenjutsu` },
    { label: `Ninshu`, value: `Ninshu` },
    { label: `Kinjutsu`, value: `Kinjutsu` },
    { label: `Taijutsu`, value: `Taijutsu` },
    { label: `Reincarnation Ninjutsu`, value: `Reincarnation Ninjutsu` },
    { label: `Nintaijutsu`, value: `Nintaijutsu` },
    { label: `Kekkei Tota`, value: `Kekkei Tota` },
    { label: `Fuinjutsu`, value: `Fuinjutsu` },
    { label: `Fighting Style`, value: `Fighting Style` },
    { label: `Barrier Ninjutsu`, value: `Barrier Ninjutsu` },
    { label: `Cooperation Ninjutsu`, value: `Cooperation Ninjutsu` },
    { label: `Jujutsu`, value: `Jujutsu` },
    { label: `Genjutsu`, value: `Genjutsu` },
    { label: `Ninjutsu`, value: `Ninjutsu` },
    { label: `Medical Ninjutsu`, value: `Medical Ninjutsu` },
    { label: `Kenjutsu`, value: `Kenjutsu` },
    { label: `Fighting style`, value: `Fighting style` },
    { label: `Kyujutsu`, value: `Kyujutsu` },
    { label: `Dojutsu`, value: `Dojutsu` },
    { label: `Juinjutsu`, value: `Juinjutsu` },
    { label: `Collaboration Techniques`, value: `Collaboration Techniques` },
    { label: `Kekkei Mora`, value: `Kekkei Mora` },
    { label: `Bukijutsu`, value: `Bukijutsu` },
    { label: `Clone Techniques`, value: `Clone Techniques` },
    { label: `Space–Time Ninjutsu`, value: `Space–Time Ninjutsu` },
    { label: `Kekkei Genkai`, value: `Kekkei Genkai` },
    { label: `Without Classification`, value: `` },
  ],
};

export const filterTypes = {
  title: `Types`,
  fields: [
    { label: `Earth Release`, value: `Earth Release` },
    { label: `Water Release`, value: `Water Release` },
    { label: `Water`, value: `Water` },
    { label: `Crystal Release`, value: `Crystal Release` },
    { label: `Magnet Release`, value: `Magnet Release` },
    { label: `Lava Release`, value: `Lava Release` },
    { label: `Wood Release`, value: `Wood Release` },
    { label: `Yang Release`, value: `Yang Release` },
    { label: `Yin–Yang Release`, value: `Yin–Yang Release` },
    { label: `Storm Release`, value: `Storm Release` },
    { label: `Mud Release`, value: `Mud Release` },
    { label: `Swift Release`, value: `Swift Release` },
    { label: `Dust Release`, value: `Dust Release` },
    { label: `Steel Release`, value: `Steel Release` },
    { label: `Fire Release`, value: `Fire Release` },
    { label: `Lightning Release`, value: `Lightning Release` },
    { label: `Boil Release`, value: `Boil Release` },
    { label: `Typhoon Release`, value: `Typhoon Release` },
    { label: `Ice Release`, value: `Ice Release` },
    { label: `Explosion Release`, value: `Explosion Release` },
    { label: `Wind Release`, value: `Wind Release` },
    { label: `Scorch Release`, value: `Scorch Release` },
    { label: `Yin Release`, value: `Yin Release` },
    { label: `Dark Release`, value: `Dark Release` },
    { label: `Without Type`, value: `` },
  ],
};
